### ISSUE TITLE
Unable to run in NodeJS environment

### ISSUE THREAD

**Issue by Manbearpixel** [kevlened/isomorphic-webcrypto#14]
Great project, I noticed in the specs that Node 4+ should be supported. My code appears as follows:
```
import * as webcrypto from "isomorphic-webcrypto";

export class Core implements CoreDef {
  public static test(): string {
    return webcrypto.getRandomValues(new Uint8Array(16)).toString();
  }
}
```

When ran however, the following error appears:
```
System.err: ReferenceError: window is not defined
System.err: File: "msrcrypto/dist/msrcrypto.js, line: 8287, column: 0
```

So it appears one of the dependencies your project uses still relies on the `window` object which would not be available in Node. Do you have some examples of this working with Node?

Thanks 
- P

**Comment by kevlened** [comment]
All the tests run in Node, so it works in Node: https://travis-ci.com/kevlened/isomorphic-webcrypto/builds/86928885

It looks like you may be running your code through a transpiler. Are you using Typescript?

**Comment by kevlened** [comment]
Closing for now. Feel free to reply if this is still an issue.
