### ISSUE TITLE
Use the new expo Random API

### ISSUE THREAD

**Issue by tasn** [kevlened/isomorphic-webcrypto#16]
In case you missed it, Expo finally added an API for cryptographically secure random number generation (https://docs.expo.io/versions/v33.0.0/sdk/random/) which resolves https://expo.canny.io/feature-requests/p/crypto-api

Looking forward to having it used here. Thanks a lot for all of your work!

**Comment by kevlened** [comment]
Thanks for the support! `isomorphic-webcrypto` v2 now uses `expo-random` when it's available. This should work out-of-the-box for managed apps and, after some brief testing, appears to work out-of-the-box for expo-backed bare apps too.

**Comment by kevlened** [comment]
Closing this for now

**Comment by tasn** [comment]
It wasn't me who added it, but yay, thanks! \o/

This changes everything! :)
