### ISSUE TITLE
seems like you are not using react native generatesecurerandom

### ISSUE THREAD

**Issue by sirpy** [kevlened/isomorphic-webcrypto#19]
```
const originalGetRandomValues = crypto.getRandomValues;
crypto.getRandomValues = function getRandomValues() {
  if (!secured) {
    throw new Error(`
      You must wait until the library is secure to call this method:
      crypto.ensureSecure(err => {
        if (err) throw err;
        const safeValues = crypto.getRandomValues();
      });
    `);
  }
  return originalGetRandomValues.apply(crypto, arguments);
}
```
you save and return the original crypto.getRandomValues
i'd expect you return generateSecureRandom.apply(crypto,arguments)
other wise i couldn't find anywhere else in the code you use the imported generateSecureRandom

**Comment by kevlened** [comment]
`generateSecureRandom` is async while the native `crypto.getRandomValues` is synchronous. `isomorphic-webcrypto` for React Native is backed by [msrCrypto](https://github.com/kevlened/msrCrypto), which has a synchronous `crypto.getRandomValues`, but needs to be bootstrapped with sufficient entropy to be secure. I bootstrap it [here with `generateSecureRandom`](https://github.com/kevlened/isomorphic-webcrypto/blob/741156c32c0167be8434d52fa1fdda01ac3bd80d/src/react-native.js#L43-L54).
