### ISSUE TITLE
Is `node-webcrypto-ossl` a dependency still?

### ISSUE THREAD

**Issue by CxRes** [kevlened/isomorphic-webcrypto#27]
`index.mjs` imports `node-webcrypto-ossl` which is not listed in `package.json`. However, from your logs it seems you intended to remove this in favour of `@peculiar/webcrypto`. Should one of these things be fixed?

**Comment by kevlened** [comment]
Thanks for finding this! I'm surprised nobody hit this since Sept. It's fixed in 2.3.5.

**Comment by CxRes** [comment]
Thank you! Could you please also add an `engines` property to `package.json`, since `@peculiar/webcrypto` is meant for node 10 and above.

**Comment by kevlened** [comment]
Are you running into an issue where this is necessary? Anything below 10 is deprecated.

I'm hesitant, because I'm unsure how various bundlers treat this field.

**Comment by CxRes** [comment]
Not an issue as such but I was trying to target node 8.0+ (Did not realize it is no longer maintained since Jan 2020). 

I am also hitting these problems while bundling an old piece of code. Its just good to have npm warn me about incompatibility in advance...

**Comment by kevlened** [comment]
Got it. The downstream library includes the `engines` field, which npm/yarn
*should* warn about.

https://github.com/PeculiarVentures/webcrypto/blob/master/package.json#L89
