### ISSUE TITLE
TypeError: global.document.addEventListener is not a function. React Native version 0.63.2

### ISSUE THREAD

**Issue by kaurrJaspreet** [kevlened/isomorphic-webcrypto#36]
TypeError: global.document.addEventListener is not a function. (In 'global.document.addEventListener('click', domEventHandler('click', triggerHandlers.bind(null, 'dom')), false)', 'global.document.addEventListener' is undefined)
I have to use the crypto.subtle into react native and I have installed only **isomorphic-webcrypto**  only using command **npm install isomorphic-webcrypto** . Please share the link of the documentation if there is any.

Thanks in Advance!!!!

Please let me know if I need to install any other dependency also for react native

![image](https://user-images.githubusercontent.com/53311745/97135065-4586b280-1775-11eb-9557-1ae88ca1b562.png)

**Comment by kevlened** [comment]
This seems unrelated to `isomorphic-webcrypto`. If you're using Expo, try upgrading to SDK 39, like this Expo user: https://github.com/expo/sentry-expo/issues/110#issuecomment-707047172

**Comment by kevlened** [comment]
Closing for now. If upgrading to SDK 39 doesn’t fix the issue, I’ll reopen it.

**Comment by kaurrJaspreet** [comment]
I am still not able to use it. Can you just elaborate that how can I use the importkey, generatekey and encryption/decryption in react native?
I am not able to use crypto.subtle.importKey

**Comment by kevlened** [comment]
There shouldn't be any additional requirement. What is the error message?

**Comment by kaurrJaspreet** [comment]
Whenever I import crypto from "import crypto from 'isomorphic-webcrypto';", then I got error 
TypeError: global.document.addEventListener is not a function. (In 'global.document.addEventListener('click', domEventHandler('click', triggerHandlers.bind(null, 'dom')), false)', 'global.document.addEventListener' is undefined)
I am using react native 0.63

**Comment by kaurrJaspreet** [comment]
You can also share the link of any example of React native if there is any. I need to resolve it asap.

**Comment by kevlened** [comment]
There are several example here: https://github.com/kevlened/webcrypto-react-native-examples

Are you using the `create react native app`?

**Comment by kaurrJaspreet** [comment]
yes, I have created my app using react-native init MyApp.

**Comment by arvinsim** [comment]
I am also interested in this. I am porting my Web code that use `window.crypto.subtle` to `react-native`.

All of the functions except `crypto.subtle.wrapKey` seems to be present.

What is the analog to `wrapKey` here?

**Comment by kevlened** [comment]
`wrapKey` should be the same, but it's only supported on certain algorithms. The react native implementation is [Microsoft's pure js implementation](https://github.com/microsoft/MSR-JavaScript-Crypto) with a few added tweaks. I haven't yet upgraded to their latest version, which may fix this issue.

I'll open a new issue for the upgrade. Feel free to open a new issue for your `wrapKey` issue.
