### ISSUE TITLE
Warning with react-native dependencies

### ISSUE THREAD

**Issue by lk77** [kevlened/isomorphic-webcrypto#38]
Hello,

we have a warning related to react-native in dev

https://github.com/kevlened/isomorphic-webcrypto/blob/734d23cf628c07a265366725d91e04aa9089fc7f/package.json#L66

we are using vue with pubnub, why those dependencies are in dev and not in optional ?

```
pubnub@4.29.11
    └─┬ isomorphic-webcrypto@2.3.6
      └── @unimodules/react-native-adapter@6.1.0
```

For what i understand you need it in your tests, so you could install it in your test scripts, like in the .travis.yml file with a :
```
npm i react-native --no-save
```

thanks

**Comment by kevlened** [comment]
That's fair, I'll move `react-native` to optional.

**Comment by lk77** [comment]
thanks !

**Comment by kevlened** [comment]
`react-native` is now an `optionalDependency` in 2.3.7

Thanks for reporting!

**Comment by kevlened** [comment]
Unfortunately, the default for `npm install` is to include `optionalDependencies` by default. This causes anyone not using `react-native` to install it by default. Unfortunately, I don't think that's worth the cost of fixing the warning, so I'll be reverting the change.

**Comment by lk77** [comment]
Arf, ok nevermind

**Comment by lk77** [comment]
I believe my issue was misleading, sorry,

it's seems that the warning is cause by this optional dependency : `@unimodules/react-native-adapter`
